[package]
name = "ragnordb-exec"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ragnordb-common = { path = "../ragnordb-common" }
ragnordb-catalog = { path = "../ragnordb-catalog" }
ragnordb-sql = { path = "../ragnordb-sql" }
ragnordb-storage = { path = "../ragnordb-storage" }
ragnordb-tablet = { path = "../ragnordb-tablet" }
ragnordb-txn = { path = "../ragnordb-txn" }