node_id = 1
data_dir = "./data/n1"
listen_addr = "127.0.0.1:7101"
admin_addr = "127.0.0.1:7201"
max_connections = 100

cluster_id = "ragnordb-dev"
bootstrap = true

[[seed_nodes]]
id = 1
raft_addr = "127.0.0.1:7001"
sql_addr = "127.0.0.1:7101"
admin_addr = "127.0.0.1:7201"

[[seed_nodes]]
id = 2
raft_addr = "127.0.0.1:7002"
sql_addr = "127.0.0.1:7102"
admin_addr = "127.0.0.1:7202"

[[seed_nodes]]
id = 3
raft_addr = "127.0.0.1:7003"
sql_addr = "127.0.0.1:7103"
admin_addr = "127.0.0.1:7203"