// This file is @generated by prost-build.
/// Durable record for one transaction committed by the single node engine
///
/// A-WAL provides record framing, checksums, ordering, and durability.
/// this message contains the database state transition required for
/// deterministic MVCC reconstruction during startup recovery
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SingleNodeTxnCommit {
    /// Version of this payload schema
    #[prost(uint32, tag = "1")]
    pub version: u32,
    /// Table owned by the local tablet that accepted the mutation batch
    #[prost(message, optional, tag = "2")]
    pub table_id: ::core::option::Option<super::ids::TableId>,
    /// Stable identity of the transaction that produced this commit
    #[prost(message, optional, tag = "3")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    /// Snapshot timestamp used for transaction conflict validation
    #[prost(message, optional, tag = "4")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    /// Timestamp at which the entire mutation batch became visible
    #[prost(message, optional, tag = "5")]
    pub commit_timestamp: ::core::option::Option<super::ids::Timestamp>,
    /// Complete transaction mutation batch in deterministic key order
    #[prost(message, repeated, tag = "6")]
    pub writes: ::prost::alloc::vec::Vec<WalWrite>,
}
/// One encoded row mutation within a committed transaction batch
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WalWrite {
    /// Canonical encoded row key, including the table namespace.
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "wal_write::Mutation", tags = "2, 3")]
    pub mutation: ::core::option::Option<wal_write::Mutation>,
}
/// Nested message and enum types in `WalWrite`.
pub mod wal_write {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Mutation {
        /// Complete canonical encoded row for an insert or update.
        #[prost(bytes, tag = "2")]
        PutRow(::prost::alloc::vec::Vec<u8>),
        /// Explicit row-deletion marker.
        #[prost(message, tag = "3")]
        Delete(super::DeleteMarker),
    }
}
/// Presence of this message represents a deletion
///
/// An empty marker avoids boolean default-value ambiguity while keeping Put and
/// Delete structurally exclusive through protobuf's `oneof`
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteMarker {}
/// durable envelope for one catalog state transition
///
/// the enclosed CatalogCommand is shared with the later replicated catalog path
/// the envelope adds single node recovery metadata without creating a second
/// representation for catalog operations
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CatalogUpdate {
    /// Version of this payload schema
    #[prost(uint32, tag = "1")]
    pub version: u32,
    /// Timestamp assigned to this catalog state transition
    #[prost(message, optional, tag = "2")]
    pub update_timestamp: ::core::option::Option<super::ids::Timestamp>,
    /// Table affected by the enclosed catalog operation
    #[prost(message, optional, tag = "3")]
    pub table_id: ::core::option::Option<super::ids::TableId>,
    /// Complete catalog operation applied during replay
    #[prost(message, optional, tag = "4")]
    pub command: ::core::option::Option<super::command::CatalogCommand>,
}
