// This file is @generated by prost-build.
/// Commands committed through the metadata Raft group.
///
/// Metadata owns desired cluster topology and SQL/catalog state. It deliberately
/// does not own:
///    - the current Raft leader, which is transient observation/cache state;
///    - committed voters/learners, which belong to each group's Raft ConfState.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetadataCommand {
    #[prost(uint32, tag = "1")]
    pub format_version: u32,
    #[prost(oneof = "metadata_command::Command", tags = "2, 3, 4, 5, 6, 7, 8")]
    pub command: ::core::option::Option<metadata_command::Command>,
}
/// Nested message and enum types in `MetadataCommand`.
pub mod metadata_command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag = "2")]
        ClusterInitialized(super::ClusterInitialized),
        #[prost(message, tag = "3")]
        RegisterNode(super::RegisterNode),
        #[prost(message, tag = "4")]
        CreateTable(super::CreateTable),
        #[prost(message, tag = "5")]
        CreateTablet(super::CreateTablet),
        #[prost(message, tag = "6")]
        SetDesiredReplicaPlacement(super::SetDesiredReplicaPlacement),
        #[prost(message, tag = "7")]
        UpdateTableSchema(super::UpdateTableSchema),
        /// Phase 5.2 authoritative CREATE TABLE transition. The metadata state
        /// machine assigns all cluster-global identities when this entry applies.
        #[prost(message, tag = "8")]
        CreateTableTopology(super::CreateTableTopology),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterInitialized {
    #[prost(string, tag = "1")]
    pub cluster_id: ::prost::alloc::string::String,
}
/// Durable physical-node directory record.
///
/// Field 2 was used by the pre-Phase-5 experimental format for one generic
/// endpoint. It must never be reinterpreted as one of the production addresses.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeDescriptor {
    #[prost(message, optional, tag = "1")]
    pub node_id: ::core::option::Option<super::ids::NodeId>,
    #[prost(string, tag = "3")]
    pub raft_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub snapshot_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub sql_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub admin_addr: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterNode {
    #[prost(message, optional, tag = "1")]
    pub node: ::core::option::Option<NodeDescriptor>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTable {
    #[prost(message, optional, tag = "1")]
    pub table: ::core::option::Option<super::catalog::TableDefinition>,
}
/// Unallocated SQL schema submitted to metadata Raft.
///
/// The proposer supplies schema semantics only. Table/tablet/Raft identities,
/// schema version, tablet count and desired placement are metadata decisions.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTableTopology {
    #[prost(string, tag = "1")]
    pub table_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub columns: ::prost::alloc::vec::Vec<super::catalog::ColumnDefinition>,
    #[prost(uint64, repeated, tag = "3")]
    pub primary_key_column_ids: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HashPartition {
    /// Zero-based bucket number.
    #[prost(uint32, tag = "1")]
    pub bucket: u32,
    /// Total number of hash buckets for this table.
    #[prost(uint32, tag = "2")]
    pub bucket_count: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PartitionSpec {
    #[prost(oneof = "partition_spec::Kind", tags = "1")]
    pub kind: ::core::option::Option<partition_spec::Kind>,
}
/// Nested message and enum types in `PartitionSpec`.
pub mod partition_spec {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Hash(super::HashPartition),
    }
}
/// Stable mapping from one logical tablet to one Raft group.
///
/// Field 5 was schema_version in the experimental metadata format. Schema
/// version belongs to the table definition and would become stale on every
/// schema update, so that field is permanently retired.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TabletDescriptor {
    #[prost(message, optional, tag = "1")]
    pub tablet_id: ::core::option::Option<super::ids::TabletId>,
    #[prost(message, optional, tag = "2")]
    pub table_id: ::core::option::Option<super::ids::TableId>,
    #[prost(message, optional, tag = "3")]
    pub raft_group_id: ::core::option::Option<super::ids::RaftGroupId>,
    #[prost(uint64, tag = "4")]
    pub tablet_epoch: u64,
    #[prost(message, optional, tag = "6")]
    pub partition: ::core::option::Option<PartitionSpec>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CreateTablet {
    #[prost(message, optional, tag = "1")]
    pub tablet: ::core::option::Option<TabletDescriptor>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DesiredReplica {
    #[prost(message, optional, tag = "1")]
    pub replica_id: ::core::option::Option<super::ids::ReplicaId>,
    #[prost(message, optional, tag = "2")]
    pub node_id: ::core::option::Option<super::ids::NodeId>,
    #[prost(enumeration = "DesiredReplicaRole", tag = "3")]
    pub role: i32,
}
/// Desired membership for one tablet.
///
/// configuration_epoch is metadata authority only. It must not be interpreted
/// as the Raft ConfState version. Reconciliation compares this desired state to
/// the independently committed ConfState of the tablet Raft group.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetDesiredReplicaPlacement {
    #[prost(message, optional, tag = "1")]
    pub tablet_id: ::core::option::Option<super::ids::TabletId>,
    #[prost(uint64, tag = "2")]
    pub configuration_epoch: u64,
    #[prost(message, repeated, tag = "3")]
    pub replicas: ::prost::alloc::vec::Vec<DesiredReplica>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateTableSchema {
    #[prost(uint64, tag = "1")]
    pub expected_schema_version: u64,
    #[prost(message, optional, tag = "2")]
    pub table: ::core::option::Option<super::catalog::TableDefinition>,
}
/// Permanent record that one consensus identity has ended.
///
/// Replica IDs are scoped to one Raft group, so the tombstone key is the full
/// (raft_group_id, replica_id) pair.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RetiredReplicaLifetime {
    #[prost(message, optional, tag = "1")]
    pub raft_group_id: ::core::option::Option<super::ids::RaftGroupId>,
    #[prost(message, optional, tag = "2")]
    pub replica_id: ::core::option::Option<super::ids::ReplicaId>,
}
/// Monotonic identity high-water marks owned by metadata.
///
/// These values survive removal of visible metadata objects. A future DROP TABLE
/// must never make an old identity allocatable again.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MetadataAllocatorState {
    #[prost(uint64, tag = "1")]
    pub max_table_id: u64,
    #[prost(uint64, tag = "2")]
    pub max_tablet_id: u64,
    #[prost(uint64, tag = "3")]
    pub max_raft_group_id: u64,
}
/// Deterministic snapshot of the metadata Raft state machine.
///
/// All repeated fields are serialized in ascending stable-ID order. This gives
/// one canonical representation for the same logical metadata projection.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetadataSnapshot {
    #[prost(uint32, tag = "1")]
    pub format_version: u32,
    /// The metadata group may technically snapshot before ClusterInitialized.
    /// Keep that state representable instead of manufacturing a cluster ID.
    #[prost(bool, tag = "2")]
    pub initialized: bool,
    #[prost(string, tag = "3")]
    pub cluster_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub nodes: ::prost::alloc::vec::Vec<NodeDescriptor>,
    #[prost(message, repeated, tag = "5")]
    pub tables: ::prost::alloc::vec::Vec<super::catalog::TableDefinition>,
    #[prost(message, repeated, tag = "6")]
    pub tablets: ::prost::alloc::vec::Vec<TabletDescriptor>,
    #[prost(message, repeated, tag = "7")]
    pub desired_placements: ::prost::alloc::vec::Vec<SetDesiredReplicaPlacement>,
    #[prost(message, repeated, tag = "8")]
    pub retired_replicas: ::prost::alloc::vec::Vec<RetiredReplicaLifetime>,
    #[prost(message, optional, tag = "9")]
    pub allocator_state: ::core::option::Option<MetadataAllocatorState>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DesiredReplicaRole {
    Unspecified = 0,
    Voter = 1,
    Learner = 2,
}
impl DesiredReplicaRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DESIRED_REPLICA_ROLE_UNSPECIFIED",
            Self::Voter => "DESIRED_REPLICA_ROLE_VOTER",
            Self::Learner => "DESIRED_REPLICA_ROLE_LEARNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DESIRED_REPLICA_ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "DESIRED_REPLICA_ROLE_VOTER" => Some(Self::Voter),
            "DESIRED_REPLICA_ROLE_LEARNER" => Some(Self::Learner),
            _ => None,
        }
    }
}
