// This file is @generated by prost-build.
/// logical database state carried by one checksummed snapshot file
///
/// the fixed width file envelope owns the magic bytes, format version, encoded
/// body length, and checksum. this protobuf body owns database semantics
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DatabaseSnapshot {
    #[prost(uint64, tag = "1")]
    pub snapshot_id: u64,
    #[prost(message, optional, tag = "2")]
    pub snapshot_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub replay_from_lsn: u64,
    #[prost(message, optional, tag = "4")]
    pub high_water_marks: ::core::option::Option<AllocatorHighWaterMarks>,
    #[prost(message, repeated, tag = "5")]
    pub tables: ::prost::alloc::vec::Vec<SnapshotTable>,
}
/// durable maxima required to prevent allocator reuse after WAL pruning
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AllocatorHighWaterMarks {
    #[prost(message, optional, tag = "1")]
    pub max_transaction_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub max_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub max_table_id: ::core::option::Option<super::ids::TableId>,
    #[prost(uint64, tag = "4")]
    pub max_snapshot_id: u64,
}
/// complete catalog and MVCC state for one table
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SnapshotTable {
    #[prost(message, optional, tag = "1")]
    pub definition: ::core::option::Option<super::catalog::TableDefinition>,
    #[prost(message, repeated, tag = "2")]
    pub default_values: ::prost::alloc::vec::Vec<DefaultValueEntry>,
    #[prost(message, repeated, tag = "3")]
    pub locks: ::prost::alloc::vec::Vec<LockEntry>,
    #[prost(message, repeated, tag = "4")]
    pub writes: ::prost::alloc::vec::Vec<WriteEntry>,
}
/// one value from default/{row_key}/{start_timestamp}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DefaultValueEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(bytes = "vec", tag = "3")]
    pub row: ::prost::alloc::vec::Vec<u8>,
}
/// one unresolved lock from lock/{row_key}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub record: ::core::option::Option<super::mvcc::LockRecord>,
}
/// one write-history record from write/{row_key}/{write_timestamp}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub write_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub record: ::core::option::Option<super::mvcc::WriteRecord>,
}
