// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ColumnDefinition {
    #[prost(uint64, tag = "1")]
    pub column_id: u64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "DataType", tag = "3")]
    pub r#type: i32,
    #[prost(bool, tag = "4")]
    pub nullable: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TableDefinition {
    #[prost(message, optional, tag = "1")]
    pub table_id: ::core::option::Option<super::ids::TableId>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub columns: ::prost::alloc::vec::Vec<ColumnDefinition>,
    #[prost(uint64, repeated, tag = "4")]
    pub primary_key_column_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, tag = "5")]
    pub schema_version: u64,
    #[prost(uint32, tag = "6")]
    pub tablet_count: u32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DataType {
    Unspecified = 0,
    Int = 1,
    Text = 2,
    Bool = 3,
}
impl DataType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DATA_TYPE_UNSPECIFIED",
            Self::Int => "DATA_TYPE_INT",
            Self::Text => "DATA_TYPE_TEXT",
            Self::Bool => "DATA_TYPE_BOOL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DATA_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "DATA_TYPE_INT" => Some(Self::Int),
            "DATA_TYPE_TEXT" => Some(Self::Text),
            "DATA_TYPE_BOOL" => Some(Self::Bool),
            _ => None,
        }
    }
}
