// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TabletCommand {
    #[prost(oneof = "tablet_command::Command", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub command: ::core::option::Option<tablet_command::Command>,
}
/// Nested message and enum types in `TabletCommand`.
pub mod tablet_command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag = "1")]
        Prewrite(super::PrewriteCommand),
        #[prost(message, tag = "2")]
        Commit(super::CommitCommand),
        #[prost(message, tag = "3")]
        Rollback(super::RollbackCommand),
        #[prost(message, tag = "4")]
        SingleShardCommit(super::SingleShardCommitCommand),
        #[prost(message, tag = "5")]
        ResolveIntent(super::ResolveIntentCommand),
        #[prost(message, tag = "6")]
        CatalogUpdate(super::CatalogCommand),
        #[prost(message, tag = "7")]
        Noop(super::NoopCommand),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrewriteCommand {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(bytes = "vec", tag = "3")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub value: ::core::option::Option<super::row::Value>,
    #[prost(bytes = "vec", tag = "5")]
    pub primary_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "super::mvcc::WriteKind", tag = "6")]
    pub op: i32,
    #[prost(uint64, tag = "7")]
    pub ttl_ms: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitCommand {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub commit_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(bytes = "vec", tag = "4")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RollbackCommand {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(bytes = "vec", tag = "3")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SingleShardCommitCommand {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub commit_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, repeated, tag = "4")]
    pub writes: ::prost::alloc::vec::Vec<WriteEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<super::row::Value>,
    #[prost(enumeration = "super::mvcc::WriteKind", tag = "3")]
    pub op: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResolveIntentCommand {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub start_ts: ::core::option::Option<super::ids::Timestamp>,
    #[prost(bytes = "vec", tag = "3")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "super::mvcc::TxnStatus", tag = "4")]
    pub resolved_status: i32,
    #[prost(message, optional, tag = "5")]
    pub commit_ts: ::core::option::Option<super::ids::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CatalogCommand {
    #[prost(oneof = "catalog_command::Operation", tags = "1")]
    pub operation: ::core::option::Option<catalog_command::Operation>,
}
/// Nested message and enum types in `CatalogCommand`.
pub mod catalog_command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Operation {
        #[prost(message, tag = "1")]
        CreateTable(super::CreateTableOperation),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTableOperation {
    #[prost(message, optional, tag = "1")]
    pub table_def: ::core::option::Option<super::catalog::TableDefinition>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NoopCommand {}
