// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReplicaPlacement {
    #[prost(message, optional, tag = "1")]
    pub replica_id: ::core::option::Option<super::ids::ReplicaId>,
    #[prost(message, optional, tag = "2")]
    pub node_id: ::core::option::Option<super::ids::NodeId>,
}
/// Durable, exactly-once authority for the initial identity and membership of
/// one Raft group.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RaftGroupBootstrap {
    #[prost(uint32, tag = "1")]
    pub format_version: u32,
    #[prost(string, tag = "2")]
    pub cluster_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub raft_group_id: ::core::option::Option<super::ids::RaftGroupId>,
    #[prost(uint64, tag = "4")]
    pub configuration_epoch: u64,
    #[prost(message, repeated, tag = "5")]
    pub replica_placements: ::prost::alloc::vec::Vec<ReplicaPlacement>,
    #[prost(message, repeated, tag = "6")]
    pub initial_voters: ::prost::alloc::vec::Vec<super::ids::ReplicaId>,
    #[prost(message, repeated, tag = "7")]
    pub initial_learners: ::prost::alloc::vec::Vec<super::ids::ReplicaId>,
}
