// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcFrame {
    #[prost(enumeration = "MessageType", tag = "1")]
    pub msg_type: i32,
    #[prost(message, optional, tag = "2")]
    pub raft_group_id: ::core::option::Option<super::ids::RaftGroupId>,
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TabletCommandRequest {
    #[prost(message, optional, tag = "1")]
    pub request_id: ::core::option::Option<super::ids::RequestId>,
    #[prost(message, optional, tag = "2")]
    pub command: ::core::option::Option<super::command::TabletCommand>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TabletCommandResponse {
    #[prost(message, optional, tag = "1")]
    pub request_id: ::core::option::Option<super::ids::RequestId>,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub retryable: bool,
    #[prost(bytes = "vec", tag = "6")]
    pub result_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetadataRequest {
    #[prost(oneof = "metadata_request::Request", tags = "1, 2, 3")]
    pub request: ::core::option::Option<metadata_request::Request>,
}
/// Nested message and enum types in `MetadataRequest`.
pub mod metadata_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Request {
        #[prost(message, tag = "1")]
        AllocateTimestamp(super::AllocateTimestampRequest),
        #[prost(message, tag = "2")]
        LookupTablet(super::LookupTabletRequest),
        #[prost(message, tag = "3")]
        LookupSchema(super::LookupSchemaRequest),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AllocateTimestampRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LookupTabletRequest {
    #[prost(uint64, tag = "1")]
    pub table_id: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LookupSchemaRequest {
    #[prost(uint64, tag = "1")]
    pub table_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetadataResponse {
    #[prost(oneof = "metadata_response::Response", tags = "1, 2, 3")]
    pub response: ::core::option::Option<metadata_response::Response>,
}
/// Nested message and enum types in `MetadataResponse`.
pub mod metadata_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "1")]
        AllocateTimestamp(super::AllocateTimestampResponse),
        #[prost(message, tag = "2")]
        LookupTablet(super::LookupTabletResponse),
        #[prost(message, tag = "3")]
        LookupSchema(super::LookupSchemaResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AllocateTimestampResponse {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<super::ids::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LookupTabletResponse {
    #[prost(message, optional, tag = "1")]
    pub tablet_id: ::core::option::Option<super::ids::TabletId>,
    #[prost(message, optional, tag = "2")]
    pub leader_id: ::core::option::Option<super::ids::NodeId>,
    #[prost(message, repeated, tag = "3")]
    pub replica_ids: ::prost::alloc::vec::Vec<super::ids::NodeId>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LookupSchemaResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub schema_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub schema_version: u64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    Unspecified = 0,
    RaftConsensus = 1,
    TabletCommandRequest = 2,
    TabletCommandResponse = 3,
    MetadataRequest = 4,
    MetadataResponse = 5,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MESSAGE_TYPE_UNSPECIFIED",
            Self::RaftConsensus => "MESSAGE_TYPE_RAFT_CONSENSUS",
            Self::TabletCommandRequest => "MESSAGE_TYPE_TABLET_COMMAND_REQUEST",
            Self::TabletCommandResponse => "MESSAGE_TYPE_TABLET_COMMAND_RESPONSE",
            Self::MetadataRequest => "MESSAGE_TYPE_METADATA_REQUEST",
            Self::MetadataResponse => "MESSAGE_TYPE_METADATA_RESPONSE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MESSAGE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "MESSAGE_TYPE_RAFT_CONSENSUS" => Some(Self::RaftConsensus),
            "MESSAGE_TYPE_TABLET_COMMAND_REQUEST" => Some(Self::TabletCommandRequest),
            "MESSAGE_TYPE_TABLET_COMMAND_RESPONSE" => Some(Self::TabletCommandResponse),
            "MESSAGE_TYPE_METADATA_REQUEST" => Some(Self::MetadataRequest),
            "MESSAGE_TYPE_METADATA_RESPONSE" => Some(Self::MetadataResponse),
            _ => None,
        }
    }
}
