// This file is @generated by prost-build.
/// commands committed by the metadata Raft group. This schema intentionally
/// represents desired topology only; per-group committed membership belongs to
/// the Raft ConfState and current leadership is refreshed from live Raft state
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetadataCommand {
    #[prost(uint32, tag = "1")]
    pub format_version: u32,
    #[prost(oneof = "metadata_command::Command", tags = "2, 3, 4, 5, 6, 7")]
    pub command: ::core::option::Option<metadata_command::Command>,
}
/// Nested message and enum types in `MetadataCommand`.
pub mod metadata_command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag = "2")]
        ClusterInitialized(super::ClusterInitialized),
        #[prost(message, tag = "3")]
        RegisterNode(super::RegisterNode),
        #[prost(message, tag = "4")]
        CreateTable(super::CreateTable),
        #[prost(message, tag = "5")]
        CreateTablet(super::CreateTablet),
        #[prost(message, tag = "6")]
        SetDesiredReplicaPlacement(super::SetDesiredReplicaPlacement),
        #[prost(message, tag = "7")]
        UpdateTableSchema(super::UpdateTableSchema),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterInitialized {
    #[prost(string, tag = "1")]
    pub cluster_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeDescriptor {
    #[prost(message, optional, tag = "1")]
    pub node_id: ::core::option::Option<super::ids::NodeId>,
    #[prost(string, tag = "2")]
    pub endpoint: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterNode {
    #[prost(message, optional, tag = "1")]
    pub node: ::core::option::Option<NodeDescriptor>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTable {
    #[prost(message, optional, tag = "1")]
    pub table: ::core::option::Option<super::catalog::TableDefinition>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TabletDescriptor {
    #[prost(message, optional, tag = "1")]
    pub tablet_id: ::core::option::Option<super::ids::TabletId>,
    #[prost(message, optional, tag = "2")]
    pub table_id: ::core::option::Option<super::ids::TableId>,
    #[prost(message, optional, tag = "3")]
    pub raft_group_id: ::core::option::Option<super::ids::RaftGroupId>,
    #[prost(uint64, tag = "4")]
    pub tablet_epoch: u64,
    #[prost(uint64, tag = "5")]
    pub schema_version: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CreateTablet {
    #[prost(message, optional, tag = "1")]
    pub tablet: ::core::option::Option<TabletDescriptor>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DesiredReplica {
    #[prost(message, optional, tag = "1")]
    pub replica_id: ::core::option::Option<super::ids::ReplicaId>,
    #[prost(message, optional, tag = "2")]
    pub node_id: ::core::option::Option<super::ids::NodeId>,
    #[prost(enumeration = "DesiredReplicaRole", tag = "3")]
    pub role: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetDesiredReplicaPlacement {
    #[prost(message, optional, tag = "1")]
    pub tablet_id: ::core::option::Option<super::ids::TabletId>,
    #[prost(uint64, tag = "2")]
    pub configuration_epoch: u64,
    #[prost(message, repeated, tag = "3")]
    pub replicas: ::prost::alloc::vec::Vec<DesiredReplica>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateTableSchema {
    #[prost(uint64, tag = "1")]
    pub expected_schema_version: u64,
    #[prost(message, optional, tag = "2")]
    pub table: ::core::option::Option<super::catalog::TableDefinition>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DesiredReplicaRole {
    Unspecified = 0,
    Voter = 1,
    Learner = 2,
}
impl DesiredReplicaRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DESIRED_REPLICA_ROLE_UNSPECIFIED",
            Self::Voter => "DESIRED_REPLICA_ROLE_VOTER",
            Self::Learner => "DESIRED_REPLICA_ROLE_LEARNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DESIRED_REPLICA_ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "DESIRED_REPLICA_ROLE_VOTER" => Some(Self::Voter),
            "DESIRED_REPLICA_ROLE_LEARNER" => Some(Self::Learner),
            _ => None,
        }
    }
}
