// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockRecord {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(bytes = "vec", tag = "2")]
    pub primary_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(uint64, tag = "4")]
    pub ttl_ms: u64,
    #[prost(enumeration = "WriteKind", tag = "5")]
    pub op: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WriteRecord {
    #[prost(message, optional, tag = "1")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, optional, tag = "2")]
    pub commit_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(enumeration = "WriteKind", tag = "3")]
    pub op: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TxnStatusRecord {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub commit_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(enumeration = "TxnStatus", tag = "4")]
    pub status: i32,
    #[prost(bytes = "vec", tag = "5")]
    pub primary_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, repeated, tag = "6")]
    pub participant_tablet_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(message, optional, tag = "7")]
    pub last_heartbeat_timestamp: ::core::option::Option<super::ids::Timestamp>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WriteKind {
    Unspecified = 0,
    Put = 1,
    Delete = 2,
    Rollback = 3,
}
impl WriteKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "WRITE_KIND_UNSPECIFIED",
            Self::Put => "WRITE_KIND_PUT",
            Self::Delete => "WRITE_KIND_DELETE",
            Self::Rollback => "WRITE_KIND_ROLLBACK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WRITE_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "WRITE_KIND_PUT" => Some(Self::Put),
            "WRITE_KIND_DELETE" => Some(Self::Delete),
            "WRITE_KIND_ROLLBACK" => Some(Self::Rollback),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TxnStatus {
    Unspecified = 0,
    Pending = 1,
    Committed = 2,
    Aborted = 3,
}
impl TxnStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TXN_STATUS_UNSPECIFIED",
            Self::Pending => "TXN_STATUS_PENDING",
            Self::Committed => "TXN_STATUS_COMMITTED",
            Self::Aborted => "TXN_STATUS_ABORTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TXN_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "TXN_STATUS_PENDING" => Some(Self::Pending),
            "TXN_STATUS_COMMITTED" => Some(Self::Committed),
            "TXN_STATUS_ABORTED" => Some(Self::Aborted),
            _ => None,
        }
    }
}
