// This file is @generated by prost-build.
/// logical database state carried by one checksummed snapshot file
///
/// the fixed width file envelope owns the magic bytes, format version, encoded
/// body length, and checksum. this protobuf body owns database semantics
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DatabaseSnapshot {
    #[prost(uint64, tag = "1")]
    pub snapshot_id: u64,
    #[prost(message, optional, tag = "2")]
    pub snapshot_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(uint64, tag = "3")]
    pub replay_from_lsn: u64,
    #[prost(message, optional, tag = "4")]
    pub high_water_marks: ::core::option::Option<AllocatorHighWaterMarks>,
    #[prost(message, repeated, tag = "5")]
    pub tables: ::prost::alloc::vec::Vec<SnapshotTable>,
}
/// durable maxima required to prevent allocator reuse after WAL pruning
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AllocatorHighWaterMarks {
    #[prost(message, optional, tag = "1")]
    pub max_transaction_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub max_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub max_table_id: ::core::option::Option<super::ids::TableId>,
    #[prost(uint64, tag = "4")]
    pub max_snapshot_id: u64,
}
/// complete catalog and MVCC state for one table
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SnapshotTable {
    #[prost(message, optional, tag = "1")]
    pub definition: ::core::option::Option<super::catalog::TableDefinition>,
    #[prost(message, repeated, tag = "2")]
    pub default_values: ::prost::alloc::vec::Vec<DefaultValueEntry>,
    #[prost(message, repeated, tag = "3")]
    pub locks: ::prost::alloc::vec::Vec<LockEntry>,
    #[prost(message, repeated, tag = "4")]
    pub writes: ::prost::alloc::vec::Vec<WriteEntry>,
}
/// one value from default/{row_key}/{start_timestamp}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DefaultValueEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(bytes = "vec", tag = "3")]
    pub row: ::prost::alloc::vec::Vec<u8>,
}
/// one unresolved lock from lock/{row_key}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub record: ::core::option::Option<super::mvcc::LockRecord>,
}
/// one write-history record from write/{row_key}/{write_timestamp}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub write_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub record: ::core::option::Option<super::mvcc::WriteRecord>,
}
/// versioned identity and integrity metadata for one immutable tablet snapshot
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TabletSnapshotMetadata {
    #[prost(uint32, tag = "1")]
    pub format_version: u32,
    #[prost(string, tag = "2")]
    pub cluster_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub raft_group_id: ::core::option::Option<super::ids::RaftGroupId>,
    #[prost(message, optional, tag = "4")]
    pub replica_id: ::core::option::Option<super::ids::ReplicaId>,
    #[prost(message, optional, tag = "5")]
    pub tablet_id: ::core::option::Option<super::ids::TabletId>,
    #[prost(uint64, tag = "6")]
    pub tablet_epoch: u64,
    #[prost(uint64, tag = "7")]
    pub snapshot_id: u64,
    #[prost(uint64, tag = "8")]
    pub last_included_index: u64,
    #[prost(uint64, tag = "9")]
    pub last_included_term: u64,
    #[prost(uint64, tag = "10")]
    pub configuration_version: u64,
    #[prost(message, repeated, tag = "11")]
    pub voters: ::prost::alloc::vec::Vec<super::ids::ReplicaId>,
    #[prost(message, repeated, tag = "12")]
    pub learners: ::prost::alloc::vec::Vec<super::ids::ReplicaId>,
    #[prost(message, repeated, tag = "13")]
    pub outgoing_voters: ::prost::alloc::vec::Vec<super::ids::ReplicaId>,
    #[prost(uint32, tag = "14")]
    pub storage_format_version: u32,
    #[prost(uint64, tag = "15")]
    pub total_length: u64,
    #[prost(bytes = "vec", tag = "16")]
    pub checksum: ::prost::alloc::vec::Vec<u8>,
}
/// the on-disk artifact contains metadata and the immutable state payload
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TabletSnapshotFile {
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<TabletSnapshotMetadata>,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// complete logical state for one tablet snapshot image
///
/// catalog definitions remain owned by the metadata authority. This payload
/// contains the tablet's MVCC state and replicated command deduplication state
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TabletSnapshotPayload {
    #[prost(uint32, tag = "1")]
    pub format_version: u32,
    #[prost(message, optional, tag = "2")]
    pub table_id: ::core::option::Option<super::ids::TableId>,
    #[prost(bytes = "vec", tag = "3")]
    pub tablet_state_machine: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "4")]
    pub default_values: ::prost::alloc::vec::Vec<DefaultValueEntry>,
    #[prost(message, repeated, tag = "5")]
    pub locks: ::prost::alloc::vec::Vec<LockEntry>,
    #[prost(message, repeated, tag = "6")]
    pub writes: ::prost::alloc::vec::Vec<WriteEntry>,
}
