// This file is @generated by prost-build.
/// durable proposal payload for one tablet state machine command
///
/// routing and retry metadata live inside the bytes commited by raft
/// so replay performs the same epoch validation and request
/// deduplication as live apply
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TabletCommandEnvelope {
    #[prost(uint32, tag = "1")]
    pub format_version: u32,
    #[prost(message, optional, tag = "2")]
    pub request_id: ::core::option::Option<super::ids::RequestId>,
    #[prost(message, optional, tag = "3")]
    pub tablet_id: ::core::option::Option<super::ids::TabletId>,
    #[prost(uint64, tag = "4")]
    pub expected_epoch: u64,
    #[prost(message, optional, tag = "5")]
    pub command: ::core::option::Option<TabletCommand>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TabletCommand {
    #[prost(oneof = "tablet_command::Command", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub command: ::core::option::Option<tablet_command::Command>,
}
/// Nested message and enum types in `TabletCommand`.
pub mod tablet_command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag = "1")]
        Prewrite(super::PrewriteCommand),
        #[prost(message, tag = "2")]
        Commit(super::CommitCommand),
        #[prost(message, tag = "3")]
        Rollback(super::RollbackCommand),
        #[prost(message, tag = "4")]
        SingleShardCommit(super::SingleShardCommitCommand),
        #[prost(message, tag = "5")]
        ResolveIntent(super::ResolveIntentCommand),
        #[prost(message, tag = "6")]
        CatalogUpdate(super::CatalogCommand),
        #[prost(message, tag = "7")]
        Noop(super::NoopCommand),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrewriteCommand {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(bytes = "vec", tag = "3")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub primary_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "super::mvcc::WriteKind", tag = "6")]
    pub op: i32,
    #[prost(uint64, tag = "7")]
    pub ttl_ms: u64,
    /// Required for Put and absent for Delete.
    #[prost(message, optional, tag = "8")]
    pub row: ::core::option::Option<super::row::Row>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitCommand {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub commit_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(bytes = "vec", tag = "4")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RollbackCommand {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(bytes = "vec", tag = "3")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SingleShardCommitCommand {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub commit_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(message, repeated, tag = "4")]
    pub writes: ::prost::alloc::vec::Vec<WriteEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "super::mvcc::WriteKind", tag = "3")]
    pub op: i32,
    /// required for Put and absent for Delete
    #[prost(message, optional, tag = "4")]
    pub row: ::core::option::Option<super::row::Row>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResolveIntentCommand {
    #[prost(message, optional, tag = "1")]
    pub txn_id: ::core::option::Option<super::ids::TxnId>,
    #[prost(message, optional, tag = "2")]
    pub start_timestamp: ::core::option::Option<super::ids::Timestamp>,
    #[prost(bytes = "vec", tag = "3")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "super::mvcc::TxnStatus", tag = "4")]
    pub resolved_status: i32,
    #[prost(message, optional, tag = "5")]
    pub commit_timestamp: ::core::option::Option<super::ids::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CatalogCommand {
    #[prost(oneof = "catalog_command::Operation", tags = "1")]
    pub operation: ::core::option::Option<catalog_command::Operation>,
}
/// Nested message and enum types in `CatalogCommand`.
pub mod catalog_command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Operation {
        #[prost(message, tag = "1")]
        CreateTable(super::CreateTableOperation),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTableOperation {
    #[prost(message, optional, tag = "1")]
    pub table_definition: ::core::option::Option<super::catalog::TableDefinition>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NoopCommand {}
/// replicated command metadata that must survive tablet snapshot installation
/// entries are encoded in ascending client-ID order by the domain codec
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TabletStateMachineSnapshot {
    #[prost(uint32, tag = "1")]
    pub format_version: u32,
    #[prost(message, optional, tag = "2")]
    pub tablet_id: ::core::option::Option<super::ids::TabletId>,
    #[prost(uint64, tag = "3")]
    pub tablet_epoch: u64,
    #[prost(message, repeated, tag = "4")]
    pub clients: ::prost::alloc::vec::Vec<ClientDeduplicationSnapshot>,
}
/// last applied request and cached result for one client in this Raft group
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientDeduplicationSnapshot {
    #[prost(message, optional, tag = "1")]
    pub last_request_id: ::core::option::Option<super::ids::RequestId>,
    #[prost(enumeration = "CachedTabletCommandResult", tag = "2")]
    pub cached_result: i32,
}
/// durable command results require explicit variants so a newer result cannot
/// accidentally acquire old semantics during recovery
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CachedTabletCommandResult {
    Unspecified = 0,
    Noop = 1,
    SingleShardCommit = 2,
    Prewrite = 3,
    Commit = 4,
    Rollback = 5,
    ResolveIntent = 6,
}
impl CachedTabletCommandResult {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CACHED_TABLET_COMMAND_RESULT_UNSPECIFIED",
            Self::Noop => "CACHED_TABLET_COMMAND_RESULT_NOOP",
            Self::SingleShardCommit => "CACHED_TABLET_COMMAND_RESULT_SINGLE_SHARD_COMMIT",
            Self::Prewrite => "CACHED_TABLET_COMMAND_RESULT_PREWRITE",
            Self::Commit => "CACHED_TABLET_COMMAND_RESULT_COMMIT",
            Self::Rollback => "CACHED_TABLET_COMMAND_RESULT_ROLLBACK",
            Self::ResolveIntent => "CACHED_TABLET_COMMAND_RESULT_RESOLVE_INTENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CACHED_TABLET_COMMAND_RESULT_UNSPECIFIED" => Some(Self::Unspecified),
            "CACHED_TABLET_COMMAND_RESULT_NOOP" => Some(Self::Noop),
            "CACHED_TABLET_COMMAND_RESULT_SINGLE_SHARD_COMMIT" => {
                Some(Self::SingleShardCommit)
            }
            "CACHED_TABLET_COMMAND_RESULT_PREWRITE" => Some(Self::Prewrite),
            "CACHED_TABLET_COMMAND_RESULT_COMMIT" => Some(Self::Commit),
            "CACHED_TABLET_COMMAND_RESULT_ROLLBACK" => Some(Self::Rollback),
            "CACHED_TABLET_COMMAND_RESULT_RESOLVE_INTENT" => Some(Self::ResolveIntent),
            _ => None,
        }
    }
}
